
// Dummy jobs data
const dummyJobs = [
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Senior Full Stack Developer",
    companyName: "TechCorp Solutions",
    companyLogo: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=100&h=100&fit=crop&crop=center",
    jobDescription: "We are seeking a talented Senior Full Stack Developer to join our dynamic team. You will be responsible for developing and maintaining web applications using modern technologies. The ideal candidate should have strong experience in both frontend and backend development, with a passion for creating exceptional user experiences.",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Technology",
    requiredSkills: ["React", "Node.js", "MongoDB", "TypeScript", "AWS"],
    location: "Karachi, Pakistan",
    salaryMin: 150000,
    salaryMax: 250000,
    deadline: new Date("2025-08-15"),
    isTestRequired: true,
    openings: 2,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-01-15")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "UI/UX Designer",
    companyName: "Creative Studios",
    companyLogo: "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Join our creative team as a UI/UX Designer where you'll design intuitive and engaging user interfaces for web and mobile applications. You'll work closely with developers and product managers to create seamless user experiences that delight our customers.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Design",
    requiredSkills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
    location: "Lahore, Pakistan",
    salaryMin: 80000,
    salaryMax: 120000,
    deadline: new Date("2025-08-20"),
    isTestRequired: true,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-01-20")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "DevOps Engineer",
    companyName: "CloudTech Inc",
    companyLogo: "https://images.unsplash.com/photo-1551808525-51a94da548ce?w=100&h=100&fit=crop&crop=center",
    jobDescription: "We're looking for a DevOps Engineer to help us build and maintain our cloud infrastructure. You'll be responsible for automating deployment processes, monitoring system performance, and ensuring high availability of our services.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Technology",
    requiredSkills: ["Docker", "Kubernetes", "AWS", "Jenkins", "Terraform"],
    location: "Islamabad, Pakistan",
    salaryMin: 120000,
    salaryMax: 180000,
    deadline: new Date("2025-08-25"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-01-22")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Digital Marketing Specialist",
    companyName: "Marketing Pro",
    companyLogo: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Join our marketing team to drive digital growth through innovative campaigns. You'll manage social media, create content strategies, and analyze campaign performance to maximize ROI for our clients.",
    jobType: "Full-time",
    experienceLevel: "Junior",
    category: "Marketing",
    requiredSkills: ["Social Media Marketing", "Google Ads", "Content Creation", "Analytics", "SEO"],
    location: "Karachi, Pakistan",
    salaryMin: 50000,
    salaryMax: 80000,
    deadline: new Date("2025-08-30"),
    isTestRequired: false,
    openings: 3,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-01-25")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Data Scientist",
    companyName: "DataWorks Analytics",
    companyLogo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&h=100&fit=crop&crop=center",
    jobDescription: "We're seeking a Data Scientist to analyze complex datasets and provide actionable insights. You'll work with machine learning algorithms, statistical models, and big data technologies to solve business problems.",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Technology",
    requiredSkills: ["Python", "Machine Learning", "SQL", "TensorFlow", "Statistics"],
    location: "Lahore, Pakistan",
    salaryMin: 180000,
    salaryMax: 280000,
    deadline: new Date("2025-09-05"),
    isTestRequired: true,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-01-28")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Mobile App Developer",
    companyName: "AppMakers Studio",
    companyLogo: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Join our mobile development team to create innovative mobile applications for iOS and Android platforms. You'll work on user-friendly apps that reach millions of users worldwide.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Technology",
    requiredSkills: ["React Native", "Flutter", "iOS", "Android", "Firebase"],
    location: "Islamabad, Pakistan",
    salaryMin: 100000,
    salaryMax: 150000,
    deadline: new Date("2025-09-10"),
    isTestRequired: true,
    openings: 2,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-02-01")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Product Manager",
    companyName: "InnovateHQ",
    companyLogo: "https://images.unsplash.com/photo-1553484771-047a44eee27e?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Lead product development from conception to launch. You'll work with cross-functional teams to define product strategy, gather requirements, and ensure successful product delivery that meets market needs.",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Management",
    requiredSkills: ["Product Strategy", "Agile", "Market Research", "Leadership", "Analytics"],
    location: "Karachi, Pakistan",
    salaryMin: 200000,
    salaryMax: 350000,
    deadline: new Date("2025-09-15"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-02-05")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Frontend Developer",
    companyName: "WebCraft Solutions",
    companyLogo: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Create beautiful and responsive web interfaces using modern frontend technologies. You'll collaborate with designers and backend developers to deliver exceptional user experiences.",
    jobType: "Full-time",
    experienceLevel: "Junior",
    category: "Technology",
    requiredSkills: ["React", "JavaScript", "CSS", "HTML", "Git"],
    location: "Lahore, Pakistan",
    salaryMin: 60000,
    salaryMax: 100000,
    deadline: new Date("2025-09-20"),
    isTestRequired: true,
    openings: 3,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-02-08")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Cybersecurity Analyst",
    companyName: "SecureNet Technologies",
    companyLogo: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Protect our organization's digital assets by monitoring security threats, implementing security measures, and responding to incidents. You'll work with cutting-edge security tools and technologies.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Technology",
    requiredSkills: ["Network Security", "Penetration Testing", "SIEM", "Incident Response", "Risk Assessment"],
    location: "Islamabad, Pakistan",
    salaryMin: 130000,
    salaryMax: 200000,
    deadline: new Date("2025-09-25"),
    isTestRequired: true,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-02-10")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Content Writer",
    companyName: "ContentCraft Agency",
    companyLogo: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Create engaging and SEO-optimized content for various digital platforms. You'll write blog posts, website copy, social media content, and marketing materials that drive engagement and conversions.",
    jobType: "Part-time",
    experienceLevel: "Junior",
    category: "Content",
    requiredSkills: ["Content Writing", "SEO", "Research", "Editing", "Social Media"],
    location: "Remote",
    salaryMin: 30000,
    salaryMax: 50000,
    deadline: new Date("2025-09-30"),
    isTestRequired: false,
    openings: 5,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-02-12")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Backend Developer",
    companyName: "ServerStack Solutions",
    companyLogo: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Build robust and scalable backend systems using modern technologies. You'll design APIs, optimize database performance, and ensure system reliability for high-traffic applications.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Technology",
    requiredSkills: ["Node.js", "Express", "PostgreSQL", "Redis", "Microservices"],
    location: "Karachi, Pakistan",
    salaryMin: 110000,
    salaryMax: 160000,
    deadline: new Date("2025-08-10"),
    isTestRequired: true,
    openings: 2,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-02-15")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Graphic Designer",
    companyName: "Visual Arts Studio",
    companyLogo: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Create stunning visual designs for print and digital media. You'll work on branding projects, marketing materials, and web graphics that communicate brand messages effectively.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Design",
    requiredSkills: ["Adobe Photoshop", "Illustrator", "InDesign", "Branding", "Typography"],
    location: "Lahore, Pakistan",
    salaryMin: 70000,
    salaryMax: 110000,
    deadline: new Date("2025-08-18"),
    isTestRequired: true,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-02-18")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Business Analyst",
    companyName: "Corporate Solutions Inc",
    companyLogo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Analyze business processes and requirements to drive digital transformation initiatives. You'll work with stakeholders to identify opportunities for improvement and optimize workflows.",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Business",
    requiredSkills: ["Business Analysis", "Process Mapping", "Requirements Gathering", "SQL", "Data Analysis"],
    location: "Islamabad, Pakistan",
    salaryMin: 140000,
    salaryMax: 200000,
    deadline: new Date("2025-08-22"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-02-20")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "QA Engineer",
    companyName: "QualityFirst Technologies",
    companyLogo: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Ensure software quality through comprehensive testing strategies. You'll design test cases, perform manual and automated testing, and work closely with development teams to deliver bug-free applications.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Technology",
    requiredSkills: ["Manual Testing", "Automation Testing", "Selenium", "TestNG", "Bug Tracking"],
    location: "Karachi, Pakistan",
    salaryMin: 90000,
    salaryMax: 130000,
    deadline: new Date("2025-08-28"),
    isTestRequired: true,
    openings: 2,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-02-22")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "HR Manager",
    companyName: "PeopleFirst Corp",
    companyLogo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Lead HR initiatives including recruitment, employee development, and organizational culture building. You'll create policies that foster a positive work environment and drive employee engagement.",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Human Resources",
    requiredSkills: ["Recruitment", "Employee Relations", "Performance Management", "HR Policies", "Leadership"],
    location: "Lahore, Pakistan",
    salaryMin: 120000,
    salaryMax: 180000,
    deadline: new Date("2025-09-02"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-02-25")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Sales Executive",
    companyName: "SalesForce Dynamics",
    companyLogo: "https://images.unsplash.com/photo-1556740758-90de374c12ad?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Drive revenue growth through strategic sales initiatives. You'll build relationships with clients, identify new business opportunities, and exceed sales targets in a competitive market.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Sales",
    requiredSkills: ["Sales Strategy", "Client Relations", "CRM", "Negotiation", "Lead Generation"],
    location: "Karachi, Pakistan",
    salaryMin: 80000,
    salaryMax: 120000,
    deadline: new Date("2025-09-05"),
    isTestRequired: false,
    openings: 3,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-02-28")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Machine Learning Engineer",
    companyName: "AI Innovations Lab",
    companyLogo: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Develop and deploy machine learning models to solve complex business problems. You'll work with large datasets, implement ML algorithms, and build AI-powered solutions.",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Technology",
    requiredSkills: ["Python", "TensorFlow", "PyTorch", "Deep Learning", "MLOps"],
    location: "Islamabad, Pakistan",
    salaryMin: 200000,
    salaryMax: 300000,
    deadline: new Date("2025-09-08"),
    isTestRequired: true,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-02")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "WordPress Developer",
    companyName: "WebSolutions Pro",
    companyLogo: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Create custom WordPress websites and plugins for clients. You'll work on e-commerce sites, corporate websites, and custom web applications using WordPress ecosystem.",
    jobType: "Full-time",
    experienceLevel: "Junior",
    category: "Technology",
    requiredSkills: ["WordPress", "PHP", "MySQL", "JavaScript", "WooCommerce"],
    location: "Lahore, Pakistan",
    salaryMin: 50000,
    salaryMax: 80000,
    deadline: new Date("2025-09-12"),
    isTestRequired: true,
    openings: 2,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-05")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Network Administrator",
    companyName: "NetSecure Systems",
    companyLogo: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Manage and maintain network infrastructure to ensure optimal performance and security. You'll handle network configuration, troubleshooting, and implement security protocols.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Technology",
    requiredSkills: ["Network Configuration", "Cisco", "Firewall", "VPN", "Network Security"],
    location: "Islamabad, Pakistan",
    salaryMin: 100000,
    salaryMax: 140000,
    deadline: new Date("2025-09-15"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-08")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Social Media Manager",
    companyName: "Digital Buzz Agency",
    companyLogo: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Manage social media presence across multiple platforms to build brand awareness and engagement. You'll create content strategies, run campaigns, and analyze social media metrics.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Marketing",
    requiredSkills: ["Social Media Strategy", "Content Creation", "Facebook Ads", "Instagram", "Analytics"],
    location: "Karachi, Pakistan",
    salaryMin: 60000,
    salaryMax: 90000,
    deadline: new Date("2025-09-18"),
    isTestRequired: false,
    openings: 2,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-10")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Database Administrator",
    companyName: "DataCore Solutions",
    companyLogo: "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Manage and optimize database systems to ensure data integrity and performance. You'll handle database design, backup strategies, and performance tuning for enterprise applications.",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Technology",
    requiredSkills: ["MySQL", "PostgreSQL", "Database Design", "Performance Tuning", "Backup & Recovery"],
    location: "Lahore, Pakistan",
    salaryMin: 130000,
    salaryMax: 190000,
    deadline: new Date("2025-09-22"),
    isTestRequired: true,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-12")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Video Editor",
    companyName: "Creative Media House",
    companyLogo: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Edit and produce engaging video content for various platforms including YouTube, social media, and corporate presentations. You'll work with raw footage to create compelling stories.",
    jobType: "Part-time",
    experienceLevel: "Junior",
    category: "Media",
    requiredSkills: ["Adobe Premiere Pro", "After Effects", "Video Editing", "Color Grading", "Audio Editing"],
    location: "Remote",
    salaryMin: 35000,
    salaryMax: 60000,
    deadline: new Date("2025-09-25"),
    isTestRequired: true,
    openings: 3,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-15")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Project Manager",
    companyName: "ProjectFlow Management",
    companyLogo: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Lead cross-functional teams to deliver projects on time and within budget. You'll coordinate resources, manage stakeholders, and ensure project success through effective planning and execution.",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Management",
    requiredSkills: ["Project Management", "Agile", "Scrum", "Risk Management", "Team Leadership"],
    location: "Islamabad, Pakistan",
    salaryMin: 160000,
    salaryMax: 240000,
    deadline: new Date("2025-09-28"),
    isTestRequired: false,
    openings: 2,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-18")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "SEO Specialist",
    companyName: "RankUp Digital",
    companyLogo: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Optimize websites for search engines to improve organic visibility and traffic. You'll conduct keyword research, implement SEO strategies, and track performance metrics.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Marketing",
    requiredSkills: ["SEO", "Google Analytics", "Keyword Research", "Link Building", "Technical SEO"],
    location: "Karachi, Pakistan",
    salaryMin: 70000,
    salaryMax: 100000,
    deadline: new Date("2025-10-02"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-20")
  },
  // Contract Jobs
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "React Developer",
    companyName: "Tech Contractors",
    companyLogo: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Build modern web applications using React.js for a 6-month contract project. You'll work with a dynamic team to create scalable frontend solutions.",
    jobType: "Contract",
    experienceLevel: "Mid",
    category: "Technology",
    requiredSkills: ["React", "JavaScript", "Redux", "REST APIs", "Git"],
    location: "Lahore, Pakistan",
    salaryMin: 120000,
    salaryMax: 180000,
    deadline: new Date("2025-08-15"),
    isTestRequired: true,
    openings: 2,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-22")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Python Developer",
    companyName: "CodeCraft Solutions",
    companyLogo: "https://images.unsplash.com/photo-1515378791036-0648a814c963?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Develop backend services and APIs using Python and Django. Contract position for building enterprise-level applications.",
    jobType: "Contract",
    experienceLevel: "Senior",
    category: "Technology",
    requiredSkills: ["Python", "Django", "PostgreSQL", "REST APIs", "Docker"],
    location: "Islamabad, Pakistan",
    salaryMin: 160000,
    salaryMax: 220000,
    deadline: new Date("2025-08-20"),
    isTestRequired: true,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-24")
  },
  // Freelance Jobs
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Logo Designer",
    companyName: "Creative Freelancers",
    companyLogo: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Design unique and memorable logos for various clients. Freelance project-based work with flexible schedules and creative freedom.",
    jobType: "Freelance",
    experienceLevel: "Mid",
    category: "Design",
    requiredSkills: ["Adobe Illustrator", "Logo Design", "Branding", "Typography", "Creative Thinking"],
    location: "Remote",
    salaryMin: 25000,
    salaryMax: 50000,
    deadline: new Date("2025-09-10"),
    isTestRequired: false,
    openings: 5,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-26")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Web Development Consultant",
    companyName: "Freelance Network",
    companyLogo: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Provide web development consulting services to small businesses. Help clients with website optimization, technical guidance, and development strategies.",
    jobType: "Freelance",
    experienceLevel: "Senior",
    category: "Technology",
    requiredSkills: ["Web Development", "Consulting", "PHP", "WordPress", "MySQL"],
    location: "Remote",
    salaryMin: 80000,
    salaryMax: 150000,
    deadline: new Date("2025-09-15"),
    isTestRequired: false,
    openings: 3,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-28")
  },
  // Internship Jobs
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Marketing Intern",
    companyName: "Growth Marketing Co",
    companyLogo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Learn digital marketing fundamentals while working on real campaigns. Perfect opportunity for students to gain hands-on experience in marketing.",
    jobType: "Internship",
    experienceLevel: "Junior",
    category: "Marketing",
    requiredSkills: ["Social Media", "Content Writing", "Basic Analytics", "Communication", "Creativity"],
    location: "Karachi, Pakistan",
    salaryMin: 20000,
    salaryMax: 30000,
    deadline: new Date("2025-08-10"),
    isTestRequired: false,
    openings: 4,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-03-30")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Software Development Intern",
    companyName: "Tech Academy",
    companyLogo: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Gain practical software development experience working on real projects. Learn from senior developers and contribute to cutting-edge applications.",
    jobType: "Internship",
    experienceLevel: "Junior",
    category: "Technology",
    requiredSkills: ["Programming Basics", "JavaScript", "HTML/CSS", "Problem Solving", "Teamwork"],
    location: "Lahore, Pakistan",
    salaryMin: 25000,
    salaryMax: 35000,
    deadline: new Date("2025-08-12"),
    isTestRequired: true,
    openings: 6,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-01")
  },
  // Lead Level Jobs
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Lead Software Architect",
    companyName: "Enterprise Solutions",
    companyLogo: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Lead architectural decisions for large-scale enterprise applications. Guide development teams and establish technical standards across multiple projects.",
    jobType: "Full-time",
    experienceLevel: "Lead",
    category: "Technology",
    requiredSkills: ["System Architecture", "Team Leadership", "Microservices", "Cloud Architecture", "Technical Strategy"],
    location: "Islamabad, Pakistan",
    salaryMin: 300000,
    salaryMax: 450000,
    deadline: new Date("2025-09-01"),
    isTestRequired: true,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-03")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Lead UX Designer",
    companyName: "Design Leadership",
    companyLogo: "https://images.unsplash.com/photo-1545670723-196ed0954986?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Lead UX design initiatives across multiple product lines. Mentor junior designers and establish design systems that scale across the organization.",
    jobType: "Full-time",
    experienceLevel: "Lead",
    category: "Design",
    requiredSkills: ["UX Leadership", "Design Systems", "Team Management", "User Research", "Strategic Thinking"],
    location: "Karachi, Pakistan",
    salaryMin: 250000,
    salaryMax: 350000,
    deadline: new Date("2025-09-05"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-05")
  },
  // Executive Level Jobs
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Chief Technology Officer",
    companyName: "TechVision Corp",
    companyLogo: "https://images.unsplash.com/photo-1553484771-047a44eee27e?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Drive technology strategy and innovation as CTO. Lead technology teams, make strategic technology decisions, and guide digital transformation initiatives.",
    jobType: "Full-time",
    experienceLevel: "Executive",
    category: "Management",
    requiredSkills: ["Executive Leadership", "Technology Strategy", "Digital Transformation", "Team Building", "Strategic Planning"],
    location: "Lahore, Pakistan",
    salaryMin: 500000,
    salaryMax: 800000,
    deadline: new Date("2025-10-01"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-07")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "VP of Marketing",
    companyName: "MarketLeaders Inc",
    companyLogo: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Lead global marketing strategy and brand development. Oversee marketing teams and drive revenue growth through innovative marketing campaigns.",
    jobType: "Full-time",
    experienceLevel: "Executive",
    category: "Marketing",
    requiredSkills: ["Marketing Strategy", "Brand Management", "Team Leadership", "Revenue Growth", "Global Marketing"],
    location: "Islamabad, Pakistan",
    salaryMin: 450000,
    salaryMax: 700000,
    deadline: new Date("2025-10-05"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-09")
  },
  // More Business Category Jobs
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Financial Analyst",
    companyName: "Finance Pro Solutions",
    companyLogo: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Analyze financial data and create reports to support business decision-making. Work with financial models and provide insights for strategic planning.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Business",
    requiredSkills: ["Financial Analysis", "Excel", "Financial Modeling", "Data Analysis", "Reporting"],
    location: "Karachi, Pakistan",
    salaryMin: 90000,
    salaryMax: 140000,
    deadline: new Date("2025-08-25"),
    isTestRequired: false,
    openings: 2,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-11")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Operations Manager",
    companyName: "Efficient Operations Ltd",
    companyLogo: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Oversee daily operations and improve process efficiency. Manage operational workflows and ensure smooth business operations across departments.",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Business",
    requiredSkills: ["Operations Management", "Process Improvement", "Team Leadership", "Strategic Planning", "Quality Control"],
    location: "Lahore, Pakistan",
    salaryMin: 150000,
    salaryMax: 220000,
    deadline: new Date("2025-08-30"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-13")
  },
  // More Human Resources Jobs
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "HR Specialist",
    companyName: "People Excellence",
    companyLogo: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Support HR functions including recruitment, employee relations, and HR policy implementation. Help create a positive workplace culture.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Human Resources",
    requiredSkills: ["Recruitment", "Employee Relations", "HR Policies", "Communication", "Conflict Resolution"],
    location: "Islamabad, Pakistan",
    salaryMin: 80000,
    salaryMax: 120000,
    deadline: new Date("2025-09-01"),
    isTestRequired: false,
    openings: 2,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-15")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Talent Acquisition Specialist",
    companyName: "TalentFirst Agency",
    companyLogo: "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Focus on finding and recruiting top talent for technology and business roles. Build talent pipelines and manage the full recruitment lifecycle.",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Human Resources",
    requiredSkills: ["Talent Acquisition", "Interviewing", "Sourcing", "Networking", "Assessment"],
    location: "Karachi, Pakistan",
    salaryMin: 110000,
    salaryMax: 160000,
    deadline: new Date("2025-09-05"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-17")
  },
  // More Sales Jobs
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Sales Representative",
    companyName: "SalesBoost Corp",
    companyLogo: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Generate new business opportunities and maintain client relationships. Meet sales targets and contribute to company revenue growth.",
    jobType: "Full-time",
    experienceLevel: "Junior",
    category: "Sales",
    requiredSkills: ["Sales Techniques", "Customer Service", "Communication", "Negotiation", "CRM Software"],
    location: "Lahore, Pakistan",
    salaryMin: 50000,
    salaryMax: 80000,
    deadline: new Date("2025-08-18"),
    isTestRequired: false,
    openings: 4,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-19")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Sales Manager",
    companyName: "Revenue Growth Solutions",
    companyLogo: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Lead sales team and develop sales strategies to achieve revenue targets. Coach sales representatives and build client relationships.",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Sales",
    requiredSkills: ["Sales Management", "Team Leadership", "Strategic Planning", "Client Relations", "Revenue Analysis"],
    location: "Islamabad, Pakistan",
    salaryMin: 140000,
    salaryMax: 200000,
    deadline: new Date("2025-08-22"),
    isTestRequired: false,
    openings: 1,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-21")
  },
  // More Media Jobs
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Content Creator",
    companyName: "Media Masters",
    companyLogo: "https://images.unsplash.com/photo-1533750516457-a7f992034fec?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Create engaging video and written content for social media platforms. Develop content strategies and manage brand presence across digital channels.",
    jobType: "Part-time",
    experienceLevel: "Mid",
    category: "Media",
    requiredSkills: ["Content Creation", "Video Production", "Social Media", "Photography", "Storytelling"],
    location: "Remote",
    salaryMin: 40000,
    salaryMax: 70000,
    deadline: new Date("2025-09-12"),
    isTestRequired: true,
    openings: 3,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-23")
  },
  {
    userId: "user_30Ml5bgV6xGGt45QgXLUhoI9PCJ",
    jobTitle: "Digital Media Specialist",
    companyName: "DigitalScope Agency",
    companyLogo: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=100&h=100&fit=crop&crop=center",
    jobDescription: "Manage digital media campaigns and create multimedia content. Work with various digital platforms to enhance brand visibility and engagement.",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Media",
    requiredSkills: ["Digital Marketing", "Media Planning", "Analytics", "Creative Software", "Campaign Management"],
    location: "Karachi, Pakistan",
    salaryMin: 70000,
    salaryMax: 110000,
    deadline: new Date("2025-09-15"),
    isTestRequired: false,
    openings: 2,
    contactEmail: "af912923@gmail.com",
    createdAt: new Date("2025-04-25")
  }
];
import mongoose from 'mongoose';
import "dotenv/config";
import Job from '../src/models/Job.js';

const MONGODB_URI = process.env.MONGODB_URI 



async function seedJobs() {
  await mongoose.connect(MONGODB_URI);
  await Job.deleteMany({});
  await Job.insertMany(dummyJobs);
  console.log('Dummy jobs inserted!');
  process.exit(0);
}

seedJobs().catch(err => { console.error(err); process.exit(1); });
