
// Dummy jobs data
const dummyJobs = [
  {
    jobTitle: "Frontend Developer",
    jobDescription: "Develop and maintain web applications using React.js.",
    companyName: "Webify Solutions",
    companyLogo: "https://via.placeholder.com/100x100?text=WS",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Technology",
    requiredSkills: ["React", "JavaScript",    "HTML", "CSS"],
    location: "Remote",
    salaryMin: 80000,
    salaryMax: 120000,
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    isTestRequired: false,
    openings: 2,
    contactEmail: "hr@webify.com",
    createdAt: new Date(),
    benefits: ["Remote work", "Health insurance"],
    remote: true,
    urgent: false,
    status: "active",
    userId: 'user_30KAKDkXzbkV25kqPoMRaRIuSgg',
  },
  {
    jobTitle: "Backend Developer",
    jobDescription: "Work on Node.js APIs and database integration.",
    companyName: "DataCore",
    companyLogo: "https://via.placeholder.com/100x100?text=DC",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Technology",
    requiredSkills: ["Node.js", "MongoDB", "Express"],
    location: "New York, NY",
    salaryMin: 100000,
    salaryMax: 150000,
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    isTestRequired: true,
    openings: 1,
    contactEmail: "jobs@datacore.com",
    createdAt: new Date(),
    benefits: ["401k", "Paid time off"],
    remote: false,
    urgent: true,
    status: "active",
    userId: 'user_30KAKDkXzbkV25kqPoMRaRIuSgg',
  },
  {
    jobTitle: "UI/UX Designer",
    jobDescription: "Design user interfaces and improve user experience.",
    companyName: "Designify",
    companyLogo: "https://via.placeholder.com/100x100?text=DF",
    jobType: "Part-time",
    experienceLevel: "Entry",
    category: "Design",
    requiredSkills: ["Figma", "Sketch", "Adobe XD"],
    location: "San Francisco, CA",
    salaryMin: 60000,
    salaryMax: 90000,
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    isTestRequired: false,
    openings: 1,
    contactEmail: "careers@designify.com",
    createdAt: new Date(),
    benefits: ["Flexible hours", "Creative environment"],
    remote: true,
    urgent: false,
    status: "active",
    userId: 'user_30KAKDkXzbkV25kqPoMRaRIuSgg',
  },
  {
    jobTitle: "DevOps Engineer",
    jobDescription: "Manage CI/CD pipelines and cloud infrastructure.",
    companyName: "CloudOps",
    companyLogo: "https://via.placeholder.com/100x100?text=CO",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Infrastructure",
    requiredSkills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    location: "Austin, TX",
    salaryMin: 95000,
    salaryMax: 130000,
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
    isTestRequired: false,
    openings: 1,
    contactEmail: "devops@cloudops.com",
    createdAt: new Date(),
    benefits: ["Stock options", "Remote work"],
    remote: true,
    urgent: false,
    status: "active",
    userId: 'user_30KAKDkXzbkV25kqPoMRaRIuSgg',
  },
  {
    jobTitle: "Marketing Specialist",
    jobDescription: "Plan and execute digital marketing campaigns.",
    companyName: "MarketMakers",
    companyLogo: "https://via.placeholder.com/100x100?text=MM",
    jobType: "Contract",
    experienceLevel: "Entry",
    category: "Marketing",
    requiredSkills: ["SEO", "Google Ads", "Content Writing"],
    location: "Chicago, IL",
    salaryMin: 40000,
    salaryMax: 60000,
    deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    isTestRequired: false,
    openings: 1,
    contactEmail: "apply@marketmakers.com",
    createdAt: new Date(),
    benefits: ["Flexible schedule", "Remote work"],
    remote: true,
    urgent: false,
    status: "active",
    userId: 'user_30KAKDkXzbkV25kqPoMRaRIuSgg',
  },
  {
    jobTitle: "Project Manager",
    jobDescription: "Lead software development projects and teams.",
    companyName: "AgileWorks",
    companyLogo: "https://via.placeholder.com/100x100?text=AW",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Management",
    requiredSkills: ["Agile", "Scrum", "Leadership"],
    location: "Boston, MA",
    salaryMin: 110000,
    salaryMax: 160000,
    deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
    isTestRequired: true,
    openings: 1,
    contactEmail: "pm@agileworks.com",
    createdAt: new Date(),
    benefits: ["Leadership training", "Bonus"],
    remote: false,
    urgent: true,
    status: "active",
    userId: 'user_30KAKDkXzbkV25kqPoMRaRIuSgg',
  },
];
import mongoose from 'mongoose';
import "dotenv/config";
import Job from '../src/models/Job.js';

const MONGODB_URI = process.env.MONGODB_URI 



async function seedJobs() {
  await mongoose.connect(MONGODB_URI);
  await Job.deleteMany({});
  await Job.insertMany(dummyJobs);
  console.log('Dummy jobs inserted!');
  process.exit(0);
}

seedJobs().catch(err => { console.error(err); process.exit(1); });
